name: Laravel Code Linting (Windows)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          tools: composer, cs2pr

      - name: Enable PHP Extensions
        run: echo "extension=fileinfo" >> C:\tools\php\php.ini

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run Laravel Pint
        run: vendor\\bin\\pint --test

      - name: Run PHP_CodeSniffer
        run: vendor\\bin\\phpcs --standard=PSR12 app/
